server:
  port: 8080

flog:
  name: somedayfly
  title: "my flog"
  desc: "${flog.name} is working on ${flog.title}"
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
    port: 8001
---
spring:
  profiles: uat
server:
    port: 8002